# Generated by Django 4.1 on 2022-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='resultado',
            field=models.IntegerField(editable=False),
        ),
    ]
