# Generated by Django 4.1 on 2022-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidato', '0002_alter_resultado_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='resultado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado',
            field=models.IntegerField(),
        ),
    ]
